server:
  port: 8080
  servlet:
    context-path: /custom-path

spring:
  main:
    allow-bean-definition-overriding: true

azure:
  cosmosdb:
    uri: https://cosmosdbconvergentedev.documents.azure.com:443/
    key: Dqormfg8aZmhUQ9UHAfOkD6BZkxF2t3smniH9Sxjfi0R1xP8eBU9pFN9mbz86lLIAUKDjbZ6rxjRPwGNoygaYA==
    database: dbconvergentedev

application:
  swagger:
    title: '@project.name@'
    description: '@project.description@'
    version: '@project.version@'
    contact:
      name: Telefonica del Peru
      url: https://www.telefonica.com.pe
      email: correo
    license:
      type: copyright
      url: https://www.telefonica.com.pe
  endpoints:
    business_parameters:
      get_sales_characteristics_url: https://aks-berserkers-ingress-dev.eastus2.cloudapp.azure.com/bussinesparameters/v2/parameters/033/dataparams?codComercialOperationType={commercialOperationType}
      get_risk_domain_url: https://aks-berserkers-ingress-dev.eastus2.cloudapp.azure.com/bussinesparameters/v2/parameters/034/dataparams?value={domain}
    product_order:
      create_product_order_url: https://aks-berserkers-ingress-dev.eastus2.cloudapp.azure.com/fesimple/v1/orders/createproduct
    url:
      business_parameters:
        seq_number: SEQ001
        sequential: https://aks-berserkers-ingress-dev.eastus2.cloudapp.azure.com/bussinesparameters/v2/parameters/{code}/dataparams?nomSeq={seq}
    stock:
      reserve_stock_url: https://aks-berserkers-ingress-dev.eastus2.cloudapp.azure.com/fesimple/v1/stocks/reserveStock
    payment:
      generate_cip_payment_identifier: https://aks-berserkers-ingress-dev.eastus2.cloudapp.azure.com/fesimple/api/v1/payment/paymentIdentifier/createPaymentIdentifier
  catalog-error:
    url: https://aks-berserkers-ingress-dev.eastus2.cloudapp.azure.com
