server:
  port: 8080
  servlet:
    context-path: /custom-path

spring:
  main:
    allow-bean-definition-overriding: true
  cloud:
    azure:
      eventhub:
        connection-string: Endpoint=sb://ehub-berserkers-dev.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=GmZePbavyI2GpKSzrpGpcTRa5do9mGrO0BS6KJIgDv8=
        checkpoint-storage-account: scberserkersdatadev
        checkpoint-access-key: 5WqP4sjnoPLWEDgTkj1s56XRhbMijS0DWiwRaz14dFrnfRq5yUjYTGanUz5TaS80+KnLVDNlO9JMU2AZ1NP89A==
        checkpoint-container: eventflow-orchestrator-checkpoint
    stream:
      bindings:
        input:
          destination: sales-update
          group: $Default
        output:
          destination: orchestrator-response
      eventhub:
        bindings:
          input:
            consumer:
              checkpoint-mode: PARTITION_COUNT
      default:
        producer:
          errorChannelEnabled: true

azure:
  cosmosdb:
    uri: https://cosmosdbconvergentedev.documents.azure.com:443/
    key: Dqormfg8aZmhUQ9UHAfOkD6BZkxF2t3smniH9Sxjfi0R1xP8eBU9pFN9mbz86lLIAUKDjbZ6rxjRPwGNoygaYA==
    database: dbconvergentedev

application:
  swagger:
    title: '@project.name@'
    description: '@project.description@'
    version: '@project.version@'
    contact:
      name: Telefonica del Peru
      url: https://www.telefonica.com.pe
      email: correo
    license:
      type: copyright
      url: https://www.telefonica.com.pe
  endpoints:
    business_parameters:
      get_sales_characteristics_url: http://aks-berserkers-ingress-dev.eastus2.cloudapp.azure.com/bussinesparameters/v2/parameters/033/dataparams?comercialOperationType={commercialOperationType}
    product_order:
      create_product_order_url: https://aks-berserkers-ingress-dev.eastus2.cloudapp.azure.com/fesimple/v1/orders/createproduct
    receptor:
      register_url: https://aks-berserkers-ingress-dev.eastus2.cloudapp.azure.com/fesimple/api/v1/receptor
    url:
      put_sale: https://aks-berserkers-ingress-dev.eastus2.cloudapp.azure.com/fesimple/v1/saleslead/{id}
      business_parameters:
        seq_number: SEQ001
        sequential: https://aks-berserkers-ingress-dev.eastus2.cloudapp.azure.com/bussinesparameters/v2/parameters/{code}/dataparams?nomSeq={seq}
  catalog-error:
    url: http://aks-berserkers-ingress-dev.eastus2.cloudapp.azure.com